name: EAS Build
on:
  workflow_call:
    inputs:
      platform:
        description: "Platform to build for (ios, android, or all)"
        required: false
        type: string
        default: "all"
      profile:
        description: "Build profile to use (development, preview, or production)"
        required: false
        type: string
        default: "preview"
      EXPO_PUBLIC_SUPABASE_URL:
        description: "Supabase URL for the app"
        required: false
        type: string
      EXPO_PUBLIC_SUPABASE_ANON_KEY:
        description: "Supabase anonymous key for the app"
        required: false
        type: string

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_SUPABASE_URL: ${{ inputs.EXPO_PUBLIC_SUPABASE_URL }}
      EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ inputs.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: eas build --platform ${{ inputs.platform }} --profile ${{ inputs.profile }} --non-interactive
