name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  prisma-deploy:
    uses: ./.github/workflows/_prisma-deploy.yml
    with:
      DATABASE_URL: ${{ vars.STAGING_DB_URL }}
      DIRECT_URL: ${{ vars.STAGING_DB_DIRECT_URL }}
    secrets: inherit

  functions-deploy:
    uses: ./.github/workflows/_supabase-deploy-functions.yml
    secrets: inherit
    needs: prisma-deploy

  eas-build-android:
    uses: ./.github/workflows/_eas-build.yml
    with:
      platform: "android"
      profile: "preview"
    secrets: inherit
    needs: functions-deploy

  # commented out til ios build credentials are set
  # eas-build-ios:
  #   uses: ./.github/workflows/_eas-build.yml
  #   with:
  #     platform: "ios"
  #     profile: "preview"
  #   secrets: inherit
  #   needs: supabase-deploy
