name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  supabase-deploy:
    uses: ./.github/workflows/_supabase-staging.yml
    secrets: inherit

  eas-build:
    needs: supabase-deploy
    uses: ./.github/workflows/_eas-build.yml
    with:
      platform: 'all'
      profile: 'preview'
    secrets: inherit