name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
  EXPO_PUBLIC_SUPABASE_URL: ${{ vars.EXPO_PUBLIC_SUPABASE_URL }}

jobs:
  supabase-deploy:
    uses: ./.github/workflows/_supabase-staging.yml
    secrets: inherit

  eas-build-android:
    uses: ./.github/workflows/_eas-build.yml
    with:
      platform: "android"
      profile: "preview"
    secrets: inherit
    needs: supabase-deploy

  eas-build-ios:
    uses: ./.github/workflows/_eas-build.yml
    with:
      platform: "ios"
      profile: "preview"
    secrets: inherit
    needs: supabase-deploy
