name: Deploy to Staging

on:
  pull_request:
    types: [closed]
    branches:
      - develop
  workflow_dispatch:

jobs:
  supabase-deploy:
    runs-on: ubuntu-latest
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    steps:
      - name: Supabase Deploy
        uses: ./.github/workflows/_supabase-staging.yml

  eas-build:
    needs: supabase-deploy
    uses: ./.github/workflows/_eas-build.yml
    with:
      platform: 'all'
      profile: 'preview'
    secrets: inherit