name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  supabase-deploy:
    uses: ./.github/workflows/_supabase-staging.yml
    secrets: inherit

  eas-build-android:
    uses: ./.github/workflows/_eas-build.yml
    with:
      platform: "android"
      profile: "preview"
    secrets: inherit
    needs: supabase-deploy

  # commented out til ios build credentials are set
  # eas-build-ios:
  #   uses: ./.github/workflows/_eas-build.yml
  #   with:
  #     platform: "ios"
  #     profile: "preview"
  #   secrets: inherit
  #   needs: supabase-deploy
