name: Deploy to Staging

on:
  pull_request:
    types: [closed]
    branches:
      - develop
  workflow_dispatch:

jobs:
  supabase-deploy:
    uses: ./.github/workflows/_supabase-staging.yml
    secrets: inherit

  eas-build-android:
    uses: ./.github/workflows/_eas-build.yml
    with:
      platform: "android"
      profile: "preview"
    secrets: inherit
    needs: supabase-deploy

  eas-build-ios:
    uses: ./.github/workflows/_eas-build.yml
    with:
      platform: "ios"
      profile: "preview"
    secrets: inherit
    needs: supabase-deploy
