name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Read an env variable
        run: echo "My vars.EXPO_PUBLIC_SUPABASE_ANON_KEY value is ${{ vars.EXPO_PUBLIC_SUPABASE_ANON_KEY }} (also accessible as $MY_vars.EXPO_PUBLIC_SUPABASE_ANON_KEY)"

  supabase-deploy:
    uses: ./.github/workflows/_supabase-staging.yml
    secrets: inherit

  eas-build-android:
    uses: ./.github/workflows/_eas-build.yml
    with:
      platform: "android"
      profile: "preview"
      EXPO_PUBLIC_SUPABASE_URL: ${{ vars.EXPO_PUBLIC_SUPABASE_URL }}
      EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
    secrets: inherit
    needs: supabase-deploy

  # commented out til ios build credentials are set
  # eas-build-ios:
  #   uses: ./.github/workflows/_eas-build.yml
  #   with:
  #     platform: "ios"
  #     profile: "preview"
  #   secrets: inherit
  #   needs: supabase-deploy
