name: Deploy to Staging

on:
  pull_request:
    types: [closed]
    branches:
      - develop
  workflow_dispatch:

jobs:
  supabase-deploy:
    runs-on: ubuntu-latest
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    steps:
      - name: Supabase Deploy
        uses: ./.github/actions/_supabase-staging.yml

  eas-build:
    runs-on: ubuntu-latest
    needs: supabase-deploy

    steps:
    - name: EAS Build
      uses: ./.github/actions/_eas-build.yml
      with:
        platform: 'all'
        profile: 'preview'